default: &default 
  adapter: postgresql 
  username: 
  password: 
  host: localhost 

development: 
  <<: *default 
  database: notarias_development 

test:
  <<: *default 
  database: notarias_test 

production: 
  <<: *default 
  database: notarias_production
