default: &default 
  adapter: postgresql 
  username: 
  password: 
  host: localhost 

development: 
  <<: *default 
  database: pvprep_development 

test:
  <<: *default 
  database: pvprep_test 

production: 
  <<: *default 
  database: pvprep_production
