# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365e6a66a8269d9c30253b913d56d055ac37fc88017ab1376d6f46873c02d15bf055294a67e386a1f8c0e7aee3749878d3f2d61fd6e3132297ddaca671599d32

test:
  secret_key_base: 2750383f8fb76aca77f1f53f23347e2a613633c0021c5e32ba841c4cc0f51d98464759b6a5113107186af12be4db9e4246cfb387101101c90df5a93f3a0c7d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
